name: cmip6-downscaling
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - xarray
  - dask
  - distributed
  - zarr
  - netcdf4
  - h5netcdf
  - numcodecs
  - scipy
  - cftime
  - pyproj
  - tqdm
  - matplotlib
  - shapely
  - bottleneck
  - cf_xarray
  - esmf=*=nompi*
  - esmpy=*=nompi*
  - importlib_metadata<5
  - xclim=0.47.0
  - xesmf=0.8.4
  - pint
  - sparse
  - lmoments3
  - statsmodels
  - pip
  - pip:
    - geopandas
    - fiona
    - click-plugins
    - cligj
