name: cmip6-downscaling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - xarray
  - dask
  - zarr
  - netcdf4
  - h5netcdf
  - numcodecs
  - scipy
  - cftime
  - pyproj
  - tqdm
  - matplotlib
  - geopandas
  - cdo
  - pip
  - pip:
    - xclim==0.47.0
    - xesmf==0.8.4
